import json
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


class AgentWorkflowContractTests(unittest.TestCase):
    def test_low_risk_fast_path_is_explicit_bounded_and_agent_free(self):
        routing = json.loads(
            (ROOT / ".agents" / "workflow" / "routing.yaml").read_text(
                encoding="utf-8"
            )
        )
        review_policy = json.loads(
            (ROOT / ".agents" / "workflow" / "review-policy.yaml").read_text(
                encoding="utf-8"
            )
        )

        route = routing["task_classes"]["low-risk-fast-path"]
        self.assertEqual(route["route"], ["coordinator-or-developer", "coordinator"])
        self.assertEqual(route["review_gate"], "fast_path")
        self.assertFalse(route["independent_testing_required"])
        self.assertFalse(route["independent_review_required"])
        self.assertFalse(route["installed_runtime_required_by_default"])
        self.assertIn(
            "selected-allowed-change-kind", route["required_qualification"]
        )

        fast_path = review_policy["fast_path"]
        self.assertEqual(fast_path["minimum_testers"], 0)
        self.assertEqual(fast_path["minimum_project_reviewers"], 0)
        self.assertIn("allowed-change-kind-selected", fast_path["eligibility_all"])
        self.assertIn("no-high-risk-category", fast_path["eligibility_all"])
        self.assertIn("no-production-behavior-change", fast_path["eligibility_all"])
        self.assertIn("focused-checks", fast_path["required_evidence"])
        self.assertIn("scope-expansion", fast_path["escalate_on"])
        self.assertIn("unexpected-failure", fast_path["escalate_on"])

        high_risk = set(review_policy["high_risk"]["categories"])
        self.assertTrue(high_risk.issubset(set(fast_path["disqualifying_risks"])))

    def test_agent_prompts_explain_fast_path_and_fail_closed_escalation(self):
        agents = (ROOT / "specs" / "AGENTS.md").read_text(encoding="utf-8")
        development = (
            ROOT / ".agents" / "skills" / "token-meter-development" / "SKILL.md"
        ).read_text(encoding="utf-8")
        intake = (
            ROOT / ".agents" / "skills" / "token-meter-intake" / "SKILL.md"
        ).read_text(encoding="utf-8")
        review = (ROOT / "specs" / "agent-workflow" / "REVIEW.md").read_text(
            encoding="utf-8"
        )

        for source in (agents, development, intake, review):
            self.assertIn("low-risk fast path", source.lower())
        normalized_agents = " ".join(agents.split())
        self.assertIn("no independent tester or reviewer", normalized_agents)
        self.assertIn(
            "does not require installed-runtime verification", normalized_agents
        )
        self.assertIn("escalate", development.lower())

    def test_generated_root_agent_and_review_prompts_match_their_sources(self):
        agents_source = (ROOT / "specs" / "AGENTS.md").read_text(encoding="utf-8")
        expected_agents = (
            "<!-- Generated by scripts/agent_tools.py; do not edit directly. "
            "Source: specs/AGENTS.md. -->\n\n"
            + agents_source.replace(
                "[ARCHITECTURE.md](ARCHITECTURE.md)",
                "[ARCHITECTURE.md](specs/ARCHITECTURE.md)",
            )
        )
        self.assertEqual(
            (ROOT / "AGENTS.md").read_text(encoding="utf-8"), expected_agents
        )

        review_source = (
            ROOT / "specs" / "agent-workflow" / "REVIEW.md"
        ).read_text(encoding="utf-8")
        expected_review = (
            "<!-- Generated by scripts/agent_tools.py; do not edit directly. "
            "Source: specs/agent-workflow/REVIEW.md. -->\n\n"
            + review_source
        )
        self.assertEqual(
            (ROOT / "REVIEW.md").read_text(encoding="utf-8"), expected_review
        )


if __name__ == "__main__":
    unittest.main()
